//! Turning ratings into something a running agent actually acts on.
//!
//! The mechanism is proven (`docs/FEASIBILITY.md` section 2): a hook returning
//! `hookSpecificOutput.additionalContext` reaches a live turn and the agent responds to it
//! without the user typing and without the turn being interrupted.
//!
//! The mechanism is the easy half. The wording is the hard half, because a naive dump has
//! five predictable failure modes:
//!
//! | failure | what it looks like | design answer |
//! |---|---|---|
//! | treated as a user turn | agent stops and replies "thanks for the feedback" | third-person observational voice, stated to be harness-generated |
//! | flagged as prompt injection | the agent surfaces the block to the user instead of absorbing it | never second-person commands; mirror the harness's own `system-reminder` register |
//! | over-correction | one rejected grep and a sound plan is abandoned | called a data point, not a mandate; a bare tap only suppresses the exact action |
//! | sycophancy | agent narrates to fish for approval | no tallies, no praise words, clinical register |
//! | context poisoning | the same complaint re-injected every tool call | delivered once, enforced by the store |
//!
//! Two orderings matter and both are counter-intuitive:
//!
//! Items run oldest to newest, so the **most recent lands last**. In-context recency bias
//! gives the final item disproportionate weight, which is where the freshest judgment
//! belongs. The first version of this file sorted newest-first and put the most important
//! signal in the weakest position.
//!
//! Every item pairs a concrete anchor with a generalised rule, anchor first. The rule alone
//! floats free of what triggered it; the quote alone does not transfer to a different
//! situation later.

use crate::moment::MomentKind;
use crate::ratings::{Rating, Verdict};

/// How many ratings ride in one injection.
///
/// Five, matching the 3-5 range that multishot guidance converges on. Past that the agent
/// treats the block as a list to work through rather than a signal to absorb. Overflow is
/// not lost: it stays pending and lands at the next boundary.
pub const MAX_PER_INJECTION: usize = 5;

/// Anchors are truncated so one verbose tool call cannot crowd out four other signals.
const ANCHOR_CHARS: usize = 120;

/// When it is worth interrupting nothing to say something.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Trigger {
    /// After a tool call completes. The main path: frequent during real work, and a
    /// boundary the agent was about to cross anyway, so nothing in flight is split.
    PostToolUse,
    /// The agent is about to finish. The one that matters during an unattended run, when
    /// nobody is about to type anything.
    Stop,
    /// Folded into the human's next turn.
    UserPromptSubmit,
    /// The context is about to be compacted.
    ///
    /// After compaction the agent holds a summary rather than the original turns, so this is
    /// the last point at which feedback lands against the thing it refers to. margin quotes
    /// the rated moment, so a later delivery still works, but it works better here.
    PreCompact,
}

impl Trigger {
    pub fn hook_event_name(self) -> &'static str {
        match self {
            Trigger::PostToolUse => "PostToolUse",
            Trigger::Stop => "Stop",
            Trigger::UserPromptSubmit => "UserPromptSubmit",
            Trigger::PreCompact => "PreCompact",
        }
    }
}

/// Render the block of text handed to the agent.
///
/// Returns None when there is nothing pending, and the caller must then emit no output at
/// all. Silence in the common case is what keeps this cheap and keeps the agent from
/// learning to skim past the tag.
pub fn render(ratings: &[Rating], trigger: Trigger) -> Option<String> {
    if ratings.is_empty() {
        return None;
    }

    let selected = select(ratings);
    let shown = selected.as_slice();

    let mut s = String::new();
    s.push_str(&format!(
        "<margin-signal kind=\"runtime_telemetry\" count=\"{}\">\n",
        shown.len()
    ));
    s.push_str(
        "Generated by margin, not written by the user. The user reacted to specific moments \
         of this run from a side channel. This is not a conversational turn: it expects no \
         reply, no acknowledgement, and no pause in the current task.\n\n",
    );

    for (i, r) in shown.iter().enumerate() {
        s.push_str(&format!("{}. {}\n", i + 1, headline(r)));
        s.push_str(&format!(
            "   at {} — \"{}\"\n",
            short_time(&r.at),
            anchor(r)
        ));
        s.push_str(&format!("   takeaway: {}\n", takeaway(r)));
    }

    if let Some(subject) = conflicting_subject(shown) {
        s.push_str(&format!(
            "\nTwo of these are about {subject} and point in opposite directions. Weight the \
             more recent and more specific one rather than averaging them.\n"
        ));
    }

    s.push('\n');
    s.push_str(
        "These are soft priors from a small sample. Fold them into how the rest of this \
         session proceeds; do not overhaul an approach that is otherwise working, and do not \
         restart work already done. ",
    );

    if trigger == Trigger::Stop {
        s.push_str(
            "This run is about to end. If a rejection above means the work is not actually \
             finished, continue instead of stopping. ",
        );
    } else {
        s.push_str("Continue the task now. ");
    }

    s.push_str("Do not comment on this block unless the user asks what changed.\n");
    s.push_str("</margin-signal>");
    Some(s)
}

/// Exactly the ratings a call to `render` would include.
///
/// Callers must mark these delivered rather than everything pending. Marking the whole queue
/// while rendering only the newest few silently discarded the rest: they were recorded as
/// sent and never shown to anyone.
pub fn select(ratings: &[Rating]) -> Vec<&Rating> {
    // Oldest first so the freshest judgment occupies the final, highest-weight position.
    let mut ordered: Vec<&Rating> = ratings.iter().collect();
    ordered.sort_by(|a, b| a.at.cmp(&b.at));
    // When the cap bites, drop the stalest rather than the newest.
    let start = ordered.len().saturating_sub(MAX_PER_INJECTION);
    ordered[start..].to_vec()
}

fn headline(r: &Rating) -> &'static str {
    match r.verdict {
        Verdict::Up => "APPROVED — the user reacted positively to this",
        Verdict::Down => "REJECTED — the user reacted negatively to this",
    }
}

/// What concretely happened. Deterministically extracted from the transcript, never
/// generated, so a takeaway can always be checked against a true quote.
fn anchor(r: &Rating) -> String {
    let raw = r.preview.as_deref().unwrap_or("<no preview captured>");
    let collapsed: String = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    if collapsed.chars().count() <= ANCHOR_CHARS {
        return collapsed;
    }
    collapsed.chars().take(ANCHOR_CHARS - 1).collect::<String>() + "…"
}

/// The generalised rule.
///
/// When the user typed a note, that note is the signal and is used verbatim: the human
/// already said the thing a model would only be guessing at.
///
/// When they did not, a bare tap carries polarity and nothing else. It does not say which
/// axis failed, so the takeaway stays deliberately narrow. A single unexplained tap should
/// change the next decision, not the strategy.
fn takeaway(r: &Rating) -> String {
    match (&r.note, r.verdict) {
        (Some(note), Verdict::Up) if !note.trim().is_empty() => {
            format!("keep doing this, specifically: {}", note.trim())
        }
        (Some(note), Verdict::Down) if !note.trim().is_empty() => {
            format!("stop doing this; instead: {}", note.trim())
        }
        (_, Verdict::Up) => "prefer this approach where the same choice comes up again".into(),
        (_, Verdict::Down) => {
            "at minimum do not repeat this exact action in this session; no reason was given, \
             so treat it as narrow rather than as a verdict on the wider approach"
                .into()
        }
    }
}

/// Whether two of these judgments genuinely pull against each other.
///
/// Not "some approvals and some rejections", which describes nearly every batch. A conflict
/// is the same kind of behaviour being both approved and rejected, such as one Bash call
/// approved and another rejected. Telling an agent that two unrelated judgments contradict
/// each other is worse than saying nothing, because it invites discarding both.
fn conflicting_subject(shown: &[&Rating]) -> Option<String> {
    for r in shown {
        let subject = r.subject.as_deref()?;
        let opposed = shown
            .iter()
            .any(|o| o.subject.as_deref() == Some(subject) && o.verdict != r.verdict);
        if opposed {
            return Some(subject.to_string());
        }
    }
    None
}

/// `2026-08-20T12:04:19.412Z` becomes `12:04:19`. Falls back to the raw string rather than
/// dropping a timestamp we failed to recognise.
fn short_time(rfc3339: &str) -> &str {
    rfc3339
        .split_once('T')
        .map(|(_, t)| t.split(['.', 'Z', '+']).next().unwrap_or(t))
        .unwrap_or(rfc3339)
}

/// The JSON a hook prints on stdout for Claude Code to pick up.
pub fn hook_output(context: &str, trigger: Trigger) -> String {
    serde_json::json!({
        "hookSpecificOutput": {
            "hookEventName": trigger.hook_event_name(),
            "additionalContext": context,
        }
    })
    .to_string()
}

/// A short label used when a rating has no preview of its own.
pub fn describe(kind: &MomentKind) -> String {
    match kind {
        MomentKind::Said { .. } => "something the agent said".into(),
        MomentKind::Asked { .. } => "the user's message".into(),
        MomentKind::Did { tool, .. } => format!("the {tool} call"),
        MomentKind::Thought { .. } => "a step of reasoning".into(),
    }
}

/// A short human-visible line for the agent's own window.
///
/// `additionalContext` reaches the model but the person never sees it. Without this, pressing
/// a key in another pane produces no visible effect in the window they are actually looking
/// at, which reads as broken even when it worked.
pub fn notice(ratings: &[Rating]) -> String {
    let up = ratings.iter().filter(|r| r.verdict == Verdict::Up).count();
    let down = ratings
        .iter()
        .filter(|r| r.verdict == Verdict::Down)
        .count();
    let mut parts = Vec::new();
    if up > 0 {
        parts.push(format!("{up} approved"));
    }
    if down > 0 {
        parts.push(format!("{down} rejected"));
    }
    format!("margin: {} delivered to the agent", parts.join(", "))
}

/// Hook output carrying both the model-facing context and the human-facing line.
pub fn hook_output_with_notice(context: &str, trigger: Trigger, notice: &str) -> String {
    serde_json::json!({
        "systemMessage": notice,
        "hookSpecificOutput": {
            "hookEventName": trigger.hook_event_name(),
            "additionalContext": context,
        }
    })
    .to_string()
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::moment::{Harness, MomentId};

    fn r(entry: &str, verdict: Verdict, at: &str, note: Option<&str>, preview: &str) -> Rating {
        rs(entry, verdict, at, note, preview, Some("said"))
    }

    fn rs(
        entry: &str,
        verdict: Verdict,
        at: &str,
        note: Option<&str>,
        preview: &str,
        subject: Option<&str>,
    ) -> Rating {
        Rating {
            moment: MomentId::new(Harness::ClaudeCode, "sess", entry, 0),
            verdict,
            note: note.map(str::to_string),
            at: at.to_string(),
            preview: Some(preview.to_string()),
            subject: subject.map(str::to_string),
        }
    }

    /// The caller marks exactly what select returns. Marking everything pending while
    /// rendering only the newest few retired ratings nobody ever saw.
    #[test]
    fn select_returns_exactly_what_render_shows() {
        let many: Vec<Rating> = (0..MAX_PER_INJECTION + 4)
            .map(|i| {
                r(
                    &format!("m{i}"),
                    Verdict::Up,
                    &format!("2026-08-20T12:00:{:02}Z", i),
                    None,
                    &format!("moment number {i}"),
                )
            })
            .collect();

        let chosen = select(&many);
        assert_eq!(chosen.len(), MAX_PER_INJECTION);

        let out = render(&many, Trigger::PostToolUse).unwrap();
        for c in &chosen {
            assert!(
                out.contains(c.preview.as_deref().unwrap()),
                "select returned something render did not show"
            );
        }
        // and the ones it dropped stay out of the block, so they remain pending
        assert!(!out.contains("moment number 0"));
        assert!(!out.contains("moment number 1"));
    }

    #[test]
    fn nothing_pending_means_nothing_is_said() {
        assert!(render(&[], Trigger::PostToolUse).is_none());
    }

    /// Recency bias gives the last item the most weight, so the newest rating must land
    /// there. The first version of this module had it exactly backwards.
    #[test]
    fn the_newest_rating_is_listed_last() {
        let ratings = vec![
            r(
                "old",
                Verdict::Up,
                "2026-08-20T12:00:00Z",
                None,
                "the older moment",
            ),
            r(
                "new",
                Verdict::Down,
                "2026-08-20T12:05:00Z",
                None,
                "the newer moment",
            ),
        ];
        let out = render(&ratings, Trigger::PostToolUse).unwrap();
        assert!(
            out.find("the older moment").unwrap() < out.find("the newer moment").unwrap(),
            "newest must occupy the final, highest-weight position"
        );
    }

    #[test]
    fn overflow_drops_the_stalest_not_the_newest() {
        let many: Vec<Rating> = (0..MAX_PER_INJECTION + 3)
            .map(|i| {
                r(
                    &format!("m{i}"),
                    Verdict::Up,
                    &format!("2026-08-20T12:00:{:02}Z", i),
                    None,
                    &format!("moment number {i}"),
                )
            })
            .collect();

        let out = render(&many, Trigger::PostToolUse).unwrap();
        assert_eq!(out.matches("moment number").count(), MAX_PER_INJECTION);
        assert!(
            out.contains(&format!("moment number {}", MAX_PER_INJECTION + 2)),
            "newest must survive"
        );
        assert!(
            !out.contains("moment number 0"),
            "stalest should be dropped"
        );
    }

    /// A rejection with no explanation must not read as a mandate to change strategy.
    #[test]
    fn a_bare_rejection_stays_narrow() {
        let out = render(
            &[r(
                "a",
                Verdict::Down,
                "2026-08-20T12:00:00Z",
                None,
                "Bash(grep -c x)",
            )],
            Trigger::PostToolUse,
        )
        .unwrap();
        assert!(out.contains("do not repeat this exact action"));
        assert!(out.contains("narrow rather than as a verdict on the wider approach"));
    }

    /// When the human typed a reason, that reason is the signal, verbatim.
    #[test]
    fn a_note_is_used_verbatim_and_paired_with_a_replacement() {
        let out = render(
            &[r(
                "a",
                Verdict::Down,
                "2026-08-20T12:00:00Z",
                Some("use the debug log instead"),
                "Bash(grep x)",
            )],
            Trigger::PostToolUse,
        )
        .unwrap();
        assert!(out.contains("stop doing this; instead: use the debug log instead"));
    }

    /// The register that keeps the agent from surfacing the block instead of absorbing it.
    #[test]
    fn the_voice_is_observational_not_a_spoofed_command() {
        let out = render(
            &[r("a", Verdict::Up, "2026-08-20T12:00:00Z", None, "x")],
            Trigger::PostToolUse,
        )
        .unwrap();
        assert!(out.contains("Generated by margin, not written by the user"));
        assert!(out.contains("not a conversational turn"));
        assert!(
            !out.contains("SYSTEM:"),
            "must not impersonate a system directive"
        );
        assert!(
            !out.contains("You must"),
            "must not issue second-person commands"
        );
    }

    #[test]
    fn guards_against_over_correction_and_sycophancy() {
        let out = render(
            &[r("a", Verdict::Down, "2026-08-20T12:00:00Z", None, "x")],
            Trigger::PostToolUse,
        )
        .unwrap();
        assert!(out.contains("soft priors from a small sample"));
        assert!(out.contains("do not overhaul an approach that is otherwise working"));
        // no tally and no praise words, which are the gameable signals
        for banned in ["great job", "well done", "score", "total:"] {
            assert!(
                !out.to_lowercase().contains(banned),
                "found gameable language: {banned}"
            );
        }
    }

    /// A conflict is the same behaviour judged both ways, not merely a batch containing one
    /// of each. The naive version fired on nearly every batch, which is misinformation.
    #[test]
    fn only_a_genuine_conflict_is_named() {
        let same_subject = vec![
            rs(
                "a",
                Verdict::Up,
                "2026-08-20T12:00:00Z",
                None,
                "one Bash call",
                Some("did:Bash"),
            ),
            rs(
                "b",
                Verdict::Down,
                "2026-08-20T12:01:00Z",
                None,
                "another Bash call",
                Some("did:Bash"),
            ),
        ];
        assert!(render(&same_subject, Trigger::PostToolUse)
            .unwrap()
            .contains("about did:Bash and point in opposite directions"));

        // approving some prose while rejecting a tool call is not a contradiction
        let different_subjects = vec![
            rs(
                "a",
                Verdict::Up,
                "2026-08-20T12:00:00Z",
                None,
                "good explanation",
                Some("said"),
            ),
            rs(
                "b",
                Verdict::Down,
                "2026-08-20T12:01:00Z",
                None,
                "bad grep",
                Some("did:Bash"),
            ),
        ];
        assert!(!render(&different_subjects, Trigger::PostToolUse)
            .unwrap()
            .contains("opposite directions"));

        let agreeing = vec![r("a", Verdict::Up, "2026-08-20T12:00:00Z", None, "one way")];
        assert!(!render(&agreeing, Trigger::PostToolUse)
            .unwrap()
            .contains("opposite directions"));
    }

    #[test]
    fn the_stop_trigger_tells_the_agent_not_to_finish_prematurely() {
        let one = [r("a", Verdict::Down, "2026-08-20T12:00:00Z", None, "x")];
        assert!(render(&one, Trigger::Stop)
            .unwrap()
            .contains("continue instead of stopping"));
        assert!(!render(&one, Trigger::PostToolUse)
            .unwrap()
            .contains("continue instead of stopping"));
    }

    /// Attention dilution, not the platform's 10k character cap, is the real constraint.
    #[test]
    fn a_full_injection_stays_within_the_attention_budget() {
        let many: Vec<Rating> = (0..MAX_PER_INJECTION)
            .map(|i| {
                r(
                    &format!("m{i}"),
                    if i % 2 == 0 {
                        Verdict::Up
                    } else {
                        Verdict::Down
                    },
                    &format!("2026-08-20T12:00:{:02}Z", i),
                    Some("a reasonably wordy explanation of what should have happened instead"),
                    &"x".repeat(400),
                )
            })
            .collect();

        let out = render(&many, Trigger::Stop).unwrap();
        let words = out.split_whitespace().count();
        assert!(
            words < 300,
            "injection grew to {words} words; budget is under 300"
        );
    }

    #[test]
    fn a_long_anchor_is_truncated_without_splitting_a_character() {
        let out = render(
            &[r(
                "a",
                Verdict::Up,
                "2026-08-20T12:00:00Z",
                None,
                &"é".repeat(500),
            )],
            Trigger::PostToolUse,
        )
        .unwrap();
        assert!(out.contains('…'), "long anchors should be clipped");
    }

    #[test]
    fn hook_output_is_the_shape_claude_code_expects() {
        let json: serde_json::Value =
            serde_json::from_str(&hook_output("hello", Trigger::PostToolUse)).unwrap();
        assert_eq!(json["hookSpecificOutput"]["hookEventName"], "PostToolUse");
        assert_eq!(json["hookSpecificOutput"]["additionalContext"], "hello");
    }

    #[test]
    fn a_malformed_timestamp_is_shown_rather_than_dropped() {
        assert_eq!(short_time("2026-08-20T12:04:19.412Z"), "12:04:19");
        assert_eq!(short_time("2026-08-20T12:04:19+02:00"), "12:04:19");
        assert_eq!(short_time("whenever"), "whenever");
    }
}
